name: Tests
on:
  pull_request:
    branches:
      - production
      - main
  workflow_dispatch:
jobs:
  laravel-tests:
    uses: code16/.github/.github/workflows/tests.yml@main
    with:
      test-command: php vendor/bin/pest
      slack-webhook-url: https://hooks.slack.com/services/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
    secrets: inherit
