name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  # Unit tests back (phpunit)
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 8.1
            env:
              LARAVEL: 9.*
              TESTBENCH: 7.*
          - php: 8.3
            env:
              LARAVEL: 11.*
              TESTBENCH: 9.*
          - php: 8.4
            env:
              LARAVEL: 11.*
              TESTBENCH: 9.*
          - php: 8.4
            env:
              LARAVEL: 12.*
              TESTBENCH: 10.*
    env: ${{ matrix.env }}
    name: P${{ matrix.php }} - L${{ matrix.env.LARAVEL }} - TB${{ matrix.env.TESTBENCH }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, mysql
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update --prefer-dist
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/pest
      - uses: 8398a7/action-slack@v3
        if: failure() && (github.base_ref == 'main' || inputs.is-package)
        with:
          status: ${{ job.status }}
          fields: job, message, author, repo
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
